trigger:
  - main

variables:
  IMAGE_NAME: aks-demo-app
  TAG: $(Build.BuildId)

  AKS_CLUSTER_NAME: aksDemoCluster
  AKS_RESOURCE_GROUP: demorg

stages:
  - stage: BuildAndPush
    displayName: Build and Push to ACR
    jobs:
      - job: DockerBuildPush
        displayName: Build and Push Image
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: 'MyACRConnection'   # ✅ Replace with your ACR Service Connection name
              repository: '$(IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: 'aks-demo-app/Dockerfile'   # ✅ Correct path to your Dockerfile
              tags: |
                $(TAG)

  - stage: DeployToAKS
    displayName: Deploy to AKS
    dependsOn: BuildAndPush
    jobs:
      - job: kub

